# Generated by Django 5.0.1 on 2024-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_scr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
